//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVoucher
    {
        public int Id { get; set; }
        public string FromFirstName { get; set; }
        public string FromLastName { get; set; }
        public string FromEmail { get; set; }
        public string FromPhone { get; set; }
        public string Message { get; set; }
        public double Amount { get; set; }
        public double Balance { get; set; }
        public bool IsGift { get; set; }
        public string ToFirstName { get; set; }
        public string ToLastName { get; set; }
        public string ToEmail { get; set; }
        public string ToPhone { get; set; }
        public string EVoucherSerialNo { get; set; }
        public string ActivationCode { get; set; }
        public bool IsLive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
