//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartItems = new HashSet<CartItem>();
            this.LikedProducts = new HashSet<LikedProduct>();
            this.PreOrders = new HashSet<PreOrder>();
            this.ReviewedProducts = new HashSet<ReviewedProduct>();
            this.Wishlists = new HashSet<Wishlist>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SubCategoryId1 { get; set; }
        public Nullable<int> SubCategoryId2 { get; set; }
        public string OriginalProductCode { get; set; }
        public string Namekey { get; set; }
        public string ColorCode { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Weight { get; set; }
        public double Height { get; set; }
        public double Width { get; set; }
        public double Length { get; set; }
        public string MoreInfo { get; set; }
        public string InStock { get; set; }
        public int StockLevel { get; set; }
        public bool IsLive { get; set; }
        public string Unit { get; set; }
        public string UnitOfPrice { get; set; }
        public Nullable<double> ImportPriceUSD { get; set; }
        public double ImportPrice { get; set; }
        public double OriginalPrice { get; set; }
        public double DiscountPrice { get; set; }
        public int NumberOfRating { get; set; }
        public int NumberOfLiked { get; set; }
        public int NumberOfReviewed { get; set; }
        public double AverageRating { get; set; }
        public string PrimaryImage { get; set; }
        public string SubImage1 { get; set; }
        public string SubImage2 { get; set; }
        public string SubImage3 { get; set; }
        public string SubImage4 { get; set; }
        public string SubImage5 { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<double> OriginalRate { get; set; }
        public Nullable<double> DiscountRate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string Materials { get; set; }
        public string Colors { get; set; }
        public string ShareLink { get; set; }
        public Nullable<int> GroupSizeId { get; set; }
        public Nullable<int> GroupColorId { get; set; }
        public string SizeName { get; set; }
        public string ColorCode1 { get; set; }
        public string ColorCode2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Category Category { get; set; }
        public virtual Category SubCategory1 { get; set; }
        public virtual Category SubCategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikedProduct> LikedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreOrder> PreOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewedProduct> ReviewedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wishlist> Wishlists { get; set; }
        public virtual Group GroupSize { get; set; }
        public virtual Group GroupColor { get; set; }
    }
}
