//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCart()
        {
            this.CartItems = new HashSet<CartItem>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public double TotalAmountExGst { get; set; }
        public double TotalAmountIncGst { get; set; }
        public double Gst { get; set; }
        public double ShippingFee { get; set; }
        public double Discount { get; set; }
        public double TotalFinalPrice { get; set; }
        public string EstimateDelivery { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public Nullable<int> ShippingPromotionId { get; set; }
        public double GSTPercent { get; set; }
        public double CreditCardSurcharge { get; set; }
        public double PayPalSurcharge { get; set; }
        public Nullable<double> FreeShippingAusPostFrom { get; set; }
        public Nullable<double> FreeShippingHomeMailFrom { get; set; }
        public Nullable<double> HomeMailDefaultPrice1 { get; set; }
        public Nullable<double> HomeMailDefaultPrice2 { get; set; }
        public Nullable<double> HomeMailDefaultPrice3 { get; set; }
        public Nullable<double> HomeMailAvailableFrom { get; set; }
        public Nullable<int> WarehousePostcode { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual Promotion ShippingPromotion { get; set; }
    }
}
